commit project
ViktorMarchuk/web-page-testing-ClickUp pull request #1
Opened 2022-12-19 17:57 UTC by ViktorMarchuk

2022-12-22 07:57 UTC, github4ta commented on src/test/java/by/it_academy/web_page_testing/ui/TestLoginPage.java
> +        StepLoginPage stepLoginPage = new StepLoginPage();
класс StepLoginPage наследуется от класса LoginPage. Это значит, что если создать объект 
`StepLoginPage **stepLoginPage** = new StepLoginPage();`
то можно иметь доступ ко всем методам родителя, т.е. класса LoginPage.

Это значит что дополнительно создавать 
`LoginPage loginPage = new LoginPage();`
не нужно!

... и так везде далее во всех тестах!

2022-12-22 07:59 UTC, github4ta commented on src/test/java/by/it_academy/web_page_testing/ui/TestLoginPage.java
> +        Assert.assertEquals(loginPage.PASSWORD_REQUIRED, loginPage.getTextPasswordRequired());
лишняя строчка кода
LoginPage loginPage = new LoginPage();

доступ к методам родителя возможен через наследника
```
Assert.assertEquals(loginPage.EMAIL_REQUIRED, **stepLoginPage**.getTextEmailRequired());
Assert.assertEquals(loginPage.PASSWORD_REQUIRED, **stepLoginPage**.getTextPasswordRequired());
```

2022-12-22 07:59 UTC, github4ta commented on src/test/java/by/it_academy/web_page_testing/ui/TestLoginPage.java
> +        Assert.assertEquals(loginPage.PASSWORD_REQUIRED, loginPage.getTextPasswordRequired());
... и так далее во всех остальных тестах!

2022-12-23 14:07 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/pages/BasePage.java
> +        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(8));
возможно, это лишнее. так как уже есть ожидание настроенное в самом драйвере.

2022-12-23 14:08 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    public final String INVALID_EMAIL = "viktor.marchuk0207@gmail";
это тестовые данные. это не часть пейдж обжекта. нужно эти значения перенести в конкретные тесты просто.

2022-12-23 14:09 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    public final String INCORRECT_EMAIL = "marchuk@tgl.by";
это тестовые данные. это не часть пейдж обжекта. нужно эти значения перенести в конкретные тесты просто.

2022-12-23 14:09 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    public final String INCORRECT_PASSWORD = GeneratingPasswordRandomWay.getPassword(VALID_NUMBERS_OF_CHARACTERS);
это тестовые данные. это не часть пейдж обжекта. нужно эти значения перенести в конкретные тесты просто.

2022-12-23 14:10 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    @FindBy(xpath = "//input[@id='login-email-input']")
можно попробовать заменить xpath на id
`@FindBy(id= "id=login-email-input")`

2022-12-23 14:11 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    @FindBy(xpath = "//input[@id='login-password-input']")
можно попробовать заменить xpath на id (см. пример выше)

2022-12-23 14:14 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    }
поскольку мы эти тестовые данные двигаем в тестовые методы. то в пейдж обжекте должны быть лить общие методы типа:
```
typeEmail(String email){
fieldEnterEmail.sendKeys(email);
}
```

```
typePassword(String password){
fieldEnterPassword.sendKeys(password);
}
```

2022-12-23 14:16 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/steps/LoginStep.java
> +    public void sameActionOnPage(){
непонятное название метода `sameActionOnPage`

2022-12-23 14:20 UTC, github4ta commented on src/test/java/by/it_academy/web_page_testing/api/TestingAPI.java
> +                .header("Authorization", token)
где-то в given можно добавтить 
.baseUri(url)
тогда when в get(endPoint)
будет без +

2022-12-23 14:22 UTC, github4ta requested changes
немножко подбросил коментов

2022-12-24 17:30 UTC, ViktorMarchuk commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    }
по моему  делая так можно вообще запутаться что откуда берется
я уже запутался, код нечитаемый, или я может не понимаю чего то

2022-12-24 17:52 UTC, ViktorMarchuk commented on src/main/java/by/it_academy/web_page_testing/ui/pages/LoginPage.java
> +    }
я так понимаю, создать геттеры в паэдже, потом в стэпе  доставать их в стэпе через общие методы ?

2023-01-02 10:16 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/steps/LoginStep.java
> +    }
конструктор и так будет вызван родителя. 
можно убрать этот конструктор.

2023-01-02 10:16 UTC, github4ta commented on src/main/java/by/it_academy/web_page_testing/ui/steps/MainStep.java
> +    }
конструктор и так будет вызван родителя. 
можно убрать этот конструктор.

2023-01-08 15:46 UTC, merged